# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendnotification',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
