# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
