# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20170729_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=256, unique=True),
        ),
    ]
