# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20170729_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
