# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170727_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height_field',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=b'', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='user',
            name='width_field',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
