# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170802_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_field',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='user',
            name='width_field',
            field=models.IntegerField(default=600),
        ),
    ]
