# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170802_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_field',
            field=models.IntegerField(blank=True, default=600, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='width_field',
            field=models.IntegerField(blank=True, default=600, null=True),
        ),
    ]
