# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170802_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', height_field='height_field', null=True, upload_to=b'', verbose_name='profile picture', width_field='width_field'),
        ),
    ]
